spring.application.name=CRUD-MUNDIAL-FELIPE-APIREST
server.port=8093

# MongoDB: si usas Atlas, puedes poner tu URI en la variable MONGODB_URI.
# Si no existe, usa MongoDB local.
spring.mongodb.uri=mongodb+srv://julianflorez2006jf_db_user:Emersonbatalla17@pcfelipe.wrrgqja.mongodb.net/Mundial?appName=pcfelipe

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
